name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac-intel
            target-arch: x86_64

          - os: macos-latest
            platform: mac-m1
            target-arch: arm64

          - os: windows-latest
            platform: windows
            target-arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable for ${{ matrix.platform }}
        run: |
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            arch -${{ matrix.target-arch }} pyinstaller --onefile steganography_tool.py
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onefile steganography_tool.py
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: steganography-${{ matrix.platform }}
          path: dist/steganography_tool*
