name: Build Steganography Tool

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to generate executable for'
        required: true
        default: 'mac-intel'
        options:
          - mac-intel
          - mac-m1
          - windows

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            platform: mac-intel
          - os: macos-latest
            platform: mac-m1
          - os: windows-latest
            platform: windows

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pillow

    - name: Build macOS Intel executable
      if: ${{ github.event.inputs.platform == 'mac-intel' }}
      run: |
        pyinstaller --onefile --target-arch=x86_64 steganography_tool.py

    - name: Build macOS M1 executable
      if: ${{ github.event.inputs.platform == 'mac-m1' }}
      run: |
        pyinstaller --onefile --target-arch=arm64 steganography_tool.py

    - name: Build Windows executable
      if: ${{ github.event.inputs.platform == 'windows' }}
      run: |
        pyinstaller --onefile steganography_tool.py

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: steganography-tool-${{ github.event.inputs.platform }}
        path: dist/steganography_tool
