name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac-m1
            runner: macos-latest
            target-arch: arm64
          - os: macos-latest
            platform: mac-intel
            runner: self-hosted  # uses your local Intel Mac
            target-arch: x86_64
          - os: windows-latest
            platform: windows
            runner: windows-latest
            target-arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        if: matrix.platform != 'mac-intel'
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Verify Python version (mac-intel)
        if: matrix.platform == 'mac-intel'
        run: python3 --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow

      - name: Build executable
        run: |
          pyinstaller --onefile steganography_tool.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-executable
          path: dist/steganography_tool

