name: Build Steganography Tool

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to generate executable for'
        required: true
        default: 'macos'
        options:
          - macos
          - windows

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pillow

    - name: Build macOS executable (Universal)
      if: ${{ matrix.platform == 'macos' }}
      run: |
        pyinstaller --onefile --target-arch=x86_64 --target-arch=arm64 steganography_tool.py

    - name: Build Windows executable
      if: ${{ matrix.platform == 'windows' }}
      run: |
        pyinstaller --onefile --platform=win32 steganography_tool.py

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: steganography-tool-${{ matrix.platform }}
        path: dist/steganography_tool
