name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac-m1
            runner: macos-latest
            target-arch: arm64
          - os: macos-latest
            platform: mac-intel
            runner: self-hosted  # uses your local Intel Mac
            target-arch: x86_64
          - os: windows-latest
            platform: windows
            runner: windows-latest
            target-arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        if: matrix.platform != 'mac-intel'
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Verify Python version (mac-intel)
        if: matrix.platform == 'mac-intel'
        run: python3 --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pillow

      - name: Build executable for steganography_hide.py
        run: |
          pyinstaller --onefile steganography_hide.py

      - name: Build executable for steganography_extract.py
        run: |
          pyinstaller --onefile steganography_extract.py

      - name: Create zip file containing both executables (Windows)
        if: matrix.platform == 'windows'
        run: |
          Compress-Archive -Path dist\steganography_hide.exe, dist\steganography_extract.exe -DestinationPath dist\steganography_executables_windows.zip

      - name: Create zip file containing both executables (macOS)
        if: matrix.platform != 'windows'
        run: |
          zip -r dist/steganography_executables_${{ matrix.platform }}.zip dist/steganography_hide dist/steganography_extract

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-executables
          path: dist/steganography_executables_${{ matrix.platform }}.zip
